# Generated by Django 4.0.5 on 2022-12-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_sender',
            name='sender',
            field=models.EmailField(max_length=100),
        ),
    ]
