# Generated by Django 4.0.5 on 2022-12-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_email_sender_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_sender',
            name='sender',
        ),
        migrations.AddField(
            model_name='email_sender',
            name='Sender',
            field=models.EmailField(max_length=150, null=True),
        ),
    ]
