# Generated by Django 4.0.5 on 2022-12-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_email_sender_sender_email_sender_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_sender',
            name='Sender',
            field=models.EmailField(max_length=254),
        ),
    ]
